[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

healthcheckPath = "/api/health"
healthcheckTimeout = 100

[env]
PORT = "5000"
